title: Welcome to Hanakotoba Blog
description: > # this means to ignore newlines
  Website where you can find plants information, facts, and photos
permalink: ':title/'
url: "https://hanakotoba.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Samuel Yang # add your name
author-img: author.jpg # add your photo
about-author: # add description
social-twitter:  # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: hanakotobablog # add your Github handle
social-email: # add your Email address

# Disqus
discus-identifier: hanakotobablog # add your discus identifier

# Tracker
analytics: UA-119541892-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"
